import polib

translations_dict = {
    "Admin": "مدير النظام",
    "Department Head": "رئيس القسم",
    "Teacher": "مدرس",
    "Invalid credentials": "بيانات الاعتماد غير صالحة",
    "You do not have permission to access this page.": "ليس لديك الصلاحية للوصول إلى هذه الصفحة.",
    "Username is required.": "اسم المستخدم مطلوب.",
    "Password must be at least 6 characters.": "يجب أن لا تقل كلمة المرور عن 6 أحرف.",
    "Full name is required.": "الاسم الكامل مطلوب.",
    "Invalid role selected.": "تم تحديد دور غير صالح.",
    "Username can only contain letters, numbers, and underscores.": "يمكن أن يحتوي اسم المستخدم على أحرف وأرقام وشرطات سفلية فقط.",
    'User "{username}" created successfully!': 'تم إنشاء المستخدم "{username}" بنجاح!',
    "Username already exists.": "اسم المستخدم موجود مسبقاً.",
    "An error occurred while creating the user.": "حدث خطأ أثناء إنشاء المستخدم.",
    "You cannot delete your own account.": "لا يمكنك حذف حسابك الخاص.",
    'User "{target_user["username"]}" deleted successfully!': 'تم حذف المستخدم "{target_user[\\"username\\"]}" بنجاح!',
    "User not found.": "المستخدم غير موجود.",
    "Invalid user ID.": "معرف المستخدم غير صالح.",
    "An error occurred while deleting the user.": "حدث خطأ أثناء حذف المستخدم.",
    'User "{old_user["username"]}" updated successfully!': 'تم تحديث المستخدم "{old_user[\\"username\\"]}" بنجاح!',
    "An error occurred while updating the user.": "حدث خطأ أثناء تحديث المستخدم.",
    'Password for "{target_user["username"]}" changed successfully!': 'تم تغيير كلمة المرور للمستخدم "{target_user[\\"username\\"]}" بنجاح!',
    "An error occurred while changing the password.": "حدث خطأ أثناء تغيير كلمة المرور.",
    "Course name cannot be empty.": "لا يمكن أن يكون اسم الدورة فارغاً.",
    'Course "{course["course_name"]}" deleted successfully.': 'تم حذف الدورة "{course[\\"course_name\\"]}" بنجاح.',
    "All fields are required.": "جميع الحقول مطلوبة.",
    "Invalid course ID.": "معرف الدورة غير صالح.",
    "A student with this ID or email already exists.": "يوجد طالب بهذا المعرف أو البريد الإلكتروني مسبقاً.",
    "Invalid student ID.": "معرف الطالب غير صالح.",
    "Student Attendance System": "نظام حضور الطلاب",
    "Student Attendance": "حضور الطلاب",
    "Dashboard": "لوحة القيادة",
    "Students": "الطلاب",
    "Courses": "الدورات",
    "Reports": "التقارير",
    "Settings": "الإعدادات",
    "Logout": "تسجيل الخروج",
    "Log out": "تسجيل الخروج",
    "Sign in to manage courses and attendance": "تسجيل الدخول لإدارة الدورات والحضور",
    "Welcome Back": "مرحباً بعودتك",
    "Username": "اسم المستخدم",
    "Password": "كلمة المرور",
    "Sign in": "تسجيل الدخول",
    "Demo Accounts": "حسابات تجريبية",
    "admin / admin123": "admin / admin123",
    "dept_head / head123": "dept_head / head123",
    "teacher1 / teacher123": "teacher1 / teacher123",
    "My Courses": "دوراتي",
    "All Courses": "جميع الدورات",
    "Course Detail": "تفاصيل الدورة",
    "Enrolled Students": "الطلاب المسجلين",
    "All Students": "جميع الطلاب",
    "Assign Students": "تعيين الطلاب",
    "Attendance Status": "حالة الحضور",
    "Session Totals": "إجماليات الجلسة",
    "Present": "حاضر",
    "Absent": "غائب",
    "Late": "متأخر",
    "Start Attendance": "بدء الحضور",
    "Save Attendance": "حفظ الحضور",
    "Cancel": "إلغاء",
    "Rename": "إعادة تسمية",
    "Delete": "حذف",
    "Update": "تحديث",
    "Export CSV": "تصدير CSV",
    "Export": "تصدير",
    "Actions": "إجراءات",
    "Edit": "تعديل",
    "Create New User": "إنشاء مستخدم جديد",
    "User Management": "إدارة المستخدمين",
    "Create, edit, and manage user accounts.": "أنشئ حسابات المستخدمين وعدّلها وأدرها.",
    "System Settings": "إعدادات النظام",
    "System Users": "مستخدمي النظام",
    "Create User": "إنشاء مستخدم",
    "User Details": "تفاصيل المستخدم",
    "Name": "الاسم",
    "Role": "الدور",
    "Email": "البريد الإلكتروني",
    "Student ID": "الرقم الجامعي",
    "Session Date": "تاريخ الجلسة",
    "Status": "الحالة",
    "Save Changes": "حفظ التغييرات",
    "Delete Course": "حذف الدورة",
    "Are you sure you want to delete this course?": "هل أنت متأكد أنك تريد حذف هذه الدورة؟",
    "Add Course": "إضافة دورة",
    "Course Name": "اسم الدورة",
    "Create Course": "إنشاء دورة",
    "Create Student": "إنشاء طالب",
    "Filter by date or status": "تصفية حسب التاريخ أو الحالة",
    "From Date": "من تاريخ",
    "To Date": "إلى تاريخ",
    "Totals by status": "الإجماليات حسب الحالة",
    "Present trend": "اتجاه الحضور",
    "Enrolled Courses": "الدورات المسجلة",
    "No courses assigned": "لا توجد دورات معينة",
    "Assign to Course": "تعيين إلى دورة",
    "View Course": "عرض الدورة",
    "Add to Course": "إضافة إلى دورة",
    "Select Student": "اختر طالبًا",
    "Edit User": "تعديل المستخدم",
    "Change Password": "تغيير كلمة المرور",
    "New Password": "كلمة المرور الجديدة",
    "Selected Student": "الطالب المحدد",
    "Search Students": "بحث عن طلاب",
    "Search students...": "البحث عن طلاب...",
    "No students found.": "لم يتم العثور على طلاب.",
    "No courses found.": "لم يتم العثور على دورات.",
    "Course Reports": "تقارير الدورات",
    "Select Course": "اختر الدورة",
    "Choose a course": "اختر دورة",
    "Open report": "فتح التقرير",
    "Open a course report to view sessions, charts, and export CSV.": "افتح تقرير الدورة لعرض الجلسات والمخططات وتصدير CSV.",
    "Full Name": "الاسم الكامل",
    "User": "المستخدم",
    "Login": "تسجيل الدخول",
    "Attendance": "الحضور",
    "Mark Attendance": "تسجيل الحضور",
    "Mark attendance": "تسجيل الحضور",
    "Started at": "بدأ في",
    "Select all": "تحديد الكل",
    "Select All": "تحديد الكل",
    "Deselect All": "إلغاء تحديد الكل",
    "0 selected": "0 محدد",
    "selected": "محدد",
    "Mark Present": "تحديد كحاضر",
    "Mark Absent": "تحديد كغائب",
    "Mark Late": "تحديد كمتأخر",
    "Student": "الطالب",
    "Student Registry": "سجل الطلاب",
    "Add students once, then assign them to courses.": "أضف الطلاب مرة واحدة، ثم قم بإسنادهم إلى الدورات.",
    "Edit student": "تعديل الطالب",
    "Enroll students": "تسجيل الطلاب",
    "Enroll selected": "تسجيل المحددين",
    "Choose students from the full stage list below": "اختر الطلاب من قائمة المرحلة الكاملة أدناه",
    "No students enrolled": "لا يوجد طلاب مسجلون",
    "Use the enrollment box to assign students to this course.": "استخدم مربع التسجيل لإسناد الطلاب إلى هذه الدورة.",
    "If a student is missing, add them in the Student Registry.": "إذا كان طالب مفقوداً، قم بإضافته في سجل الطلاب.",
    "Add students": "إضافة طلاب",
    "Enrollment restricted": "التسجيل مقيّد",
    "Only administrators and department heads can enroll students.": "يمكن فقط لمدير النظام ورئيس القسم تسجيل الطلاب.",
}

po = polib.pofile('translations/ar/LC_MESSAGES/messages.po')
for entry in po:
    if entry.msgid in translations_dict:
        entry.msgstr = translations_dict[entry.msgid]

po.save()
print("Translations generated!")
